// AUTO-GENERATED by scripts/generate-collection-index.ts. Do not edit.
//
// One static import() per model file. Written from the same pass that builds
// collection-index.json, so the two cannot drift. Regenerate with
// `npm run generate-index`; predev and prebuild both do it for you.

import type { WatchDetails } from "./watchDetails";

export const modelLoaders: Record<string, () => Promise<{ default: WatchDetails }>> = {
  "Admes/Admes_ETA1246_Automatic_1950": () =>
    import("./watchModels/Admes/Admes_ETA1246_Automatic_1950"),
  "Amer/Amer_Campos_1975_17_jewels": () => import("./watchModels/Amer/Amer_Campos_1975_17_jewels"),
  "Amer/Amer_Campos_Racing_Red_1975_17_jewels": () =>
    import("./watchModels/Amer/Amer_Campos_Racing_Red_1975_17_jewels"),
  "Amer/Amer_Campos_Racing_Yellow_1975_17_jewels": () =>
    import("./watchModels/Amer/Amer_Campos_Racing_Yellow_1975_17_jewels"),
  "Amyria/Amyria_Blue_Shades_1977": () => import("./watchModels/Amyria/Amyria_Blue_Shades_1977"),
  "Amyria/Amyria_Day_Date_1976": () => import("./watchModels/Amyria/Amyria_Day_Date_1976"),
  "Arauto/Arauto_Silver_Tuxedo_Unitas_6325_1974": () =>
    import("./watchModels/Arauto/Arauto_Silver_Tuxedo_Unitas_6325_1974"),
  "Argus/Argus_Tuxedo_Militare_1945": () =>
    import("./watchModels/Argus/Argus_Tuxedo_Militare_1945"),
  "Aureus/Aureus_Extra_Antimagnetic_1947": () =>
    import("./watchModels/Aureus/Aureus_Extra_Antimagnetic_1947"),
  "Barrett/Barrett_Gran_Turismo_ETA_2472_1965": () =>
    import("./watchModels/Barrett/Barrett_Gran_Turismo_ETA_2472_1965"),
  "Baume_et_Mercier/Baume_et_Mercier_Capeland_Noir_2005": () =>
    import("./watchModels/Baume_et_Mercier/Baume_et_Mercier_Capeland_Noir_2005"),
  "Baume_et_Mercier/Baume_et_Mercier_LeRoy_Tank_1989": () =>
    import("./watchModels/Baume_et_Mercier/Baume_et_Mercier_LeRoy_Tank_1989"),
  "Belex/Belex_Precision_17Jewels_1965": () =>
    import("./watchModels/Belex/Belex_Precision_17Jewels_1965"),
  "Bergeon/Bergeon_Incabloc_1960": () => import("./watchModels/Bergeon/Bergeon_Incabloc_1960"),
  "Breitling/Breitling_Chronomat_81_950_Olive_Dial_1993": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_81_950_Olive_Dial_1993"),
  "Breitling/Breitling_Chronomat_A13050_10th_Anniversary_1994": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_A13050_10th_Anniversary_1994"),
  "Breitling/Breitling_Chronomat_B13050_2002": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_B13050_2002"),
  "Breitling/Breitling_Chronomat_B13050_Blue_Dial_1996": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_B13050_Blue_Dial_1996"),
  "Breitling/Breitling_Chronomat_B13050_Vitesse_Black_1998": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_B13050_Vitesse_Black_1998"),
  "Breitling/Breitling_Chronomat_D13047_Serie_Speciale_1993": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_D13047_Serie_Speciale_1993"),
  "Breitling/Breitling_Chronomat_Evolution_A13356_2008": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_Evolution_A13356_2008"),
  "Breitling/Breitling_Chronomat_J13047X_1991": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_J13047X_1991"),
  "Breitling/Breitling_Chronomat_Sextant_80350_1989": () =>
    import("./watchModels/Breitling/Breitling_Chronomat_Sextant_80350_1989"),
  "Breitling/Breitling_Colt_A53035_1998": () =>
    import("./watchModels/Breitling/Breitling_Colt_A53035_1998"),
  "Breitling/Breitling_Navitimer_D30022_Tropical_dial_1992": () =>
    import("./watchModels/Breitling/Breitling_Navitimer_D30022_Tropical_dial_1992"),
  "Breitling/Breitling_Navitimer_Premier_A40035_1998": () =>
    import("./watchModels/Breitling/Breitling_Navitimer_Premier_A40035_1998"),
  "Breitling/Breitling_Premier_Chronograph_Venus_175_1948": () =>
    import("./watchModels/Breitling/Breitling_Premier_Chronograph_Venus_175_1948"),
  "Breitling/Breitling_Sextant_B55047_1998": () =>
    import("./watchModels/Breitling/Breitling_Sextant_B55047_1998"),
  "Breitling/Breitling_Vitesse_Serie_Speciale_Blue_1998": () =>
    import("./watchModels/Breitling/Breitling_Vitesse_Serie_Speciale_Blue_1998"),
  "Buren/Buren_Gran_Prix__1947": () => import("./watchModels/Buren/Buren_Gran_Prix__1947"),
  "Calypso/Calypso_OS10_Chrono_2001": () =>
    import("./watchModels/Calypso/Calypso_OS10_Chrono_2001"),
  "Camel_Trophy/Camel_Trophy_M136831839_1995": () =>
    import("./watchModels/Camel_Trophy/Camel_Trophy_M136831839_1995"),
  "Camel_Trophy/Camel_Trophy_M6612000009_1998": () =>
    import("./watchModels/Camel_Trophy/Camel_Trophy_M6612000009_1998"),
  "Camel_Trophy/Camel_Trophy_M81020802089_2001": () =>
    import("./watchModels/Camel_Trophy/Camel_Trophy_M81020802089_2001"),
  "Cauny/Cauny_Apollon_17Rubis_1957": () =>
    import("./watchModels/Cauny/Cauny_Apollon_17Rubis_1957"),
  "Cauny/Cauny_Apollon_17_jewels_1965": () =>
    import("./watchModels/Cauny/Cauny_Apollon_17_jewels_1965"),
  "Cauny/Cauny_Prima_17Rubis_1965": () => import("./watchModels/Cauny/Cauny_Prima_17Rubis_1965"),
  "Cauny/Cauny_Prima_Calendario_17Rubis_1967": () =>
    import("./watchModels/Cauny/Cauny_Prima_Calendario_17Rubis_1967"),
  "Cauny/Cauny_Prima_Calendario_17_Jewels_1967": () =>
    import("./watchModels/Cauny/Cauny_Prima_Calendario_17_Jewels_1967"),
  "Cauny/Cauny_Prima_DeLuxe_1956": () => import("./watchModels/Cauny/Cauny_Prima_DeLuxe_1956"),
  "Celsus/Celsus_9168_Heritage_2022": () =>
    import("./watchModels/Celsus/Celsus_9168_Heritage_2022"),
  "Celsus/Celsus_PPAA782XG_2015": () => import("./watchModels/Celsus/Celsus_PPAA782XG_2015"),
  "Celsus/Celsus_PPAB942G_2020": () => import("./watchModels/Celsus/Celsus_PPAB942G_2020"),
  "Certina/Certina_DS_Automatic_27_jewels_1965": () =>
    import("./watchModels/Certina/Certina_DS_Automatic_27_jewels_1965"),
  "Certina/Certina_DS_First_White_Ceramic_2014": () =>
    import("./watchModels/Certina/Certina_DS_First_White_Ceramic_2014"),
  "Certina/Certina_DS_Podium_Lady_MOP_2020": () =>
    import("./watchModels/Certina/Certina_DS_Podium_Lady_MOP_2020"),
  "Certina/Certina_Dress_331_15_jewels_1950": () =>
    import("./watchModels/Certina/Certina_Dress_331_15_jewels_1950"),
  "Chopard/Chopard_Mille_Miglia_2000_Titanium": () =>
    import("./watchModels/Chopard/Chopard_Mille_Miglia_2000_Titanium"),
  "Corticima/Corticima_Dress_17Jewels_1970": () =>
    import("./watchModels/Corticima/Corticima_Dress_17Jewels_1970"),
  "Cristal_Watch/Cristal_Watch_Blue_Cushion_17J_1975": () =>
    import("./watchModels/Cristal_Watch/Cristal_Watch_Blue_Cushion_17J_1975"),
  "Cristalor/Cristalor_Antimagnetic_17_Rubis_1965": () =>
    import("./watchModels/Cristalor/Cristalor_Antimagnetic_17_Rubis_1965"),
  "Cuervo_y_Sobrinos/Cuervo_y_Sobrinos_Hanava_Landeron_159_1950": () =>
    import("./watchModels/Cuervo_y_Sobrinos/Cuervo_y_Sobrinos_Hanava_Landeron_159_1950"),
  "Delma/Delma_RoyalGeographical_1996": () =>
    import("./watchModels/Delma/Delma_RoyalGeographical_1996"),
  "Delma/Delma_RoyalGeographical_ETA251_1996": () =>
    import("./watchModels/Delma/Delma_RoyalGeographical_ETA251_1996"),
  "Douglas/Douglas_Antimagnetic_1947": () =>
    import("./watchModels/Douglas/Douglas_Antimagnetic_1947"),
  "Doxa/Doxa_Antimagnetic_1942": () => import("./watchModels/Doxa/Doxa_Antimagnetic_1942"),
  "DuBois_Et_Fils/DuBois_Gran_Prix_Europe_F1_1999": () =>
    import("./watchModels/DuBois_Et_Fils/DuBois_Gran_Prix_Europe_F1_1999"),
  "Eberhard/Eberhard_Chronograph_31000_1980": () =>
    import("./watchModels/Eberhard/Eberhard_Chronograph_31000_1980"),
  "Eberhard/Eberhard_Chronograph_32001_Tricompax_Moon_1980": () =>
    import("./watchModels/Eberhard/Eberhard_Chronograph_32001_Tricompax_Moon_1980"),
  "Eberhard/Eberhard_Extra_Fort_1950": () =>
    import("./watchModels/Eberhard/Eberhard_Extra_Fort_1950"),
  "Eberhard/Eberhard_Godron_Ref_32031_Lemania_1873_1992": () =>
    import("./watchModels/Eberhard/Eberhard_Godron_Ref_32031_Lemania_1873_1992"),
  "Eletta/Eletta_OS60_Chrono_1993": () => import("./watchModels/Eletta/Eletta_OS60_Chrono_1993"),
  "Emes/Emes_Chrono_OS60_2005": () => import("./watchModels/Emes/Emes_Chrono_OS60_2005"),
  "Ferrari/Ferrari_Modena_Chronograph_2005": () =>
    import("./watchModels/Ferrari/Ferrari_Modena_Chronograph_2005"),
  "Ferrari/Ferrari_Monza_Chronograph_2005": () =>
    import("./watchModels/Ferrari/Ferrari_Monza_Chronograph_2005"),
  "Festina/Festina_Automatic_ETA_2452_1965": () =>
    import("./watchModels/Festina/Festina_Automatic_ETA_2452_1965"),
  "Festina/Festina_F6602_MultiFunction_1993": () =>
    import("./watchModels/Festina/Festina_F6602_MultiFunction_1993"),
  "Fontaine/Fontaine_ETA2472_Auto_1965": () =>
    import("./watchModels/Fontaine/Fontaine_ETA2472_Auto_1965"),
  "Fortis/Fortis_Mecanical_17Rubis_1955": () =>
    import("./watchModels/Fortis/Fortis_Mecanical_17Rubis_1955"),
  "Fortis/Fortis_Pilot_Chronograph_17J_1947": () =>
    import("./watchModels/Fortis/Fortis_Pilot_Chronograph_17J_1947"),
  "Girard_Perregaux/Girard_Perregaux_Ferrari_Ref_8020_2004": () =>
    import("./watchModels/Girard_Perregaux/Girard_Perregaux_Ferrari_Ref_8020_2004"),
  "Greenwich/Greenwich_Premier_ETA251_Chrono_1995": () =>
    import("./watchModels/Greenwich/Greenwich_Premier_ETA251_Chrono_1995"),
  "Helma/Helma_AS1130_1955": () => import("./watchModels/Helma/Helma_AS1130_1955"),
  "Hermes/Hermes_Landeron_51_Chrono_1955": () =>
    import("./watchModels/Hermes/Hermes_Landeron_51_Chrono_1955"),
  "Hipco/Hipco_Incabloc_17Jewels_1974": () =>
    import("./watchModels/Hipco/Hipco_Incabloc_17Jewels_1974"),
  "Jaguar/Jaguar_Frag_Chromed_OS10_1995": () =>
    import("./watchModels/Jaguar/Jaguar_Frag_Chromed_OS10_1995"),
  "Jaguar/Jaguar_Frag_Chromed_OS10_III_1995": () =>
    import("./watchModels/Jaguar/Jaguar_Frag_Chromed_OS10_III_1995"),
  "Jaguar/Jaguar_Frag_Chromed_OS10_II_1995": () =>
    import("./watchModels/Jaguar/Jaguar_Frag_Chromed_OS10_II_1995"),
  "Jomel/Jomel_Antimagnetic_Lorsa_238_1965": () =>
    import("./watchModels/Jomel/Jomel_Antimagnetic_Lorsa_238_1965"),
  "Lanco/Lanco_Cal1305_1960": () => import("./watchModels/Lanco/Lanco_Cal1305_1960"),
  "Latino/Latino_Excellence_1995": () => import("./watchModels/Latino/Latino_Excellence_1995"),
  "Lorenz/Lorenz_Classic_Chrono_7760_1996": () =>
    import("./watchModels/Lorenz/Lorenz_Classic_Chrono_7760_1996"),
  "Lorenz/Lorenz_Classic_Rattrapante_1989": () =>
    import("./watchModels/Lorenz/Lorenz_Classic_Rattrapante_1989"),
  "Lorenz/Lorenz_Classic_Rattrapante_1992": () =>
    import("./watchModels/Lorenz/Lorenz_Classic_Rattrapante_1992"),
  "Lorenz/Lorenz_Montecarlo_600ft_1987": () =>
    import("./watchModels/Lorenz/Lorenz_Montecarlo_600ft_1987"),
  "Lorus/Lorus_N945_7A10_MultiFunction_1993": () =>
    import("./watchModels/Lorus/Lorus_N945_7A10_MultiFunction_1993"),
  "Lorus/Lorus_N945_7A90_MultiFunction_1993": () =>
    import("./watchModels/Lorus/Lorus_N945_7A90_MultiFunction_1993"),
  "Lorus/Lorus_VD53_Sports_Chrono_2016": () =>
    import("./watchModels/Lorus/Lorus_VD53_Sports_Chrono_2016"),
  "Lucerne/Lucerne_Automatic_27J_1975": () =>
    import("./watchModels/Lucerne/Lucerne_Automatic_27J_1975"),
  "Lucerne/Lucerne_Three_Stars_1975": () =>
    import("./watchModels/Lucerne/Lucerne_Three_Stars_1975"),
  "Martini/Martini_Special_17Rubis_1975": () =>
    import("./watchModels/Martini/Martini_Special_17Rubis_1975"),
  "Maserati/Maserati_Neptune_Chrono_1998": () =>
    import("./watchModels/Maserati/Maserati_Neptune_Chrono_1998"),
  "Maurice_Lacroix/Maurice_Lacroix_5393_Chrono_2021": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_5393_Chrono_2021"),
  "Maurice_Lacroix/Maurice_Lacroix_5872_Chrono_2021": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_5872_Chrono_2021"),
  "Maurice_Lacroix/Maurice_Lacroix_5872_Monza_Schumacher_Chrono_1996": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_5872_Monza_Schumacher_Chrono_1996"),
  "Maurice_Lacroix/Maurice_Lacroix_8724_MasterPiece_2010": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_8724_MasterPiece_2010"),
  "Maurice_Lacroix/Maurice_Lacroix_8899_MasterPiece_2019": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_8899_MasterPiece_2019"),
  "Maurice_Lacroix/Maurice_Lacroix_Aikon_2021": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_Aikon_2021"),
  "Maurice_Lacroix/Maurice_Lacroix_Lady_Date_1998": () =>
    import("./watchModels/Maurice_Lacroix/Maurice_Lacroix_Lady_Date_1998"),
  "Mercedes/Mercedes_Benz_OS60_Chrono_2002": () =>
    import("./watchModels/Mercedes/Mercedes_Benz_OS60_Chrono_2002"),
  "Mercedes/Mercedes_Benz_SLK_Chrono_II_2004": () =>
    import("./watchModels/Mercedes/Mercedes_Benz_SLK_Chrono_II_2004"),
  "Mercedes/Mercedes_Benz_SLK_Chrono_I_2004": () =>
    import("./watchModels/Mercedes/Mercedes_Benz_SLK_Chrono_I_2004"),
  "Mercedes/Mercedes_Benz_SLK_Edition_1996": () =>
    import("./watchModels/Mercedes/Mercedes_Benz_SLK_Edition_1996"),
  "Miura/Miura_Calendar_17Rubis_1975": () =>
    import("./watchModels/Miura/Miura_Calendar_17Rubis_1975"),
  "Monumental/Monumental_Automatic_200M_1975": () =>
    import("./watchModels/Monumental/Monumental_Automatic_200M_1975"),
  "Natalis/Natalis_AS1130_1943": () => import("./watchModels/Natalis/Natalis_AS1130_1943"),
  "Nobreza/Nobreza_Automatic_1977": () => import("./watchModels/Nobreza/Nobreza_Automatic_1977"),
  "Nobreza/Nobreza_Racing_Chrono_7754_1977": () =>
    import("./watchModels/Nobreza/Nobreza_Racing_Chrono_7754_1977"),
  "Nobreza/Nobreza_Shades_Mechanical_1976": () =>
    import("./watchModels/Nobreza/Nobreza_Shades_Mechanical_1976"),
  "Novart/Novart_Incabloc_white_17Jewels_1976": () =>
    import("./watchModels/Novart/Novart_Incabloc_white_17Jewels_1976"),
  "Novart/Novart_Monza_Desert_Sand_17Jewels_197": () =>
    import("./watchModels/Novart/Novart_Monza_Desert_Sand_17Jewels_197"),
  "Novart/Novart_Monza_Green_Borealis_17J_1974": () =>
    import("./watchModels/Novart/Novart_Monza_Green_Borealis_17J_1974"),
  "Novart/Novart_Monza_Green_Borealis_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Monza_Green_Borealis_17Jewels_1974"),
  "Novart/Novart_Monza_Ligth_Blue_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Monza_Ligth_Blue_17Jewels_1974"),
  "Novart/Novart_Monza_Red_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Monza_Red_17Jewels_1974"),
  "Novart/Novart_Tides_Blue_17J_1974": () =>
    import("./watchModels/Novart/Novart_Tides_Blue_17J_1974"),
  "Novart/Novart_Tides_Blue_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Tides_Blue_17Jewels_1974"),
  "Novart/Novart_Tides_Blue_17_Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Tides_Blue_17_Jewels_1974"),
  "Novart/Novart_Tides_Blue_Borealis_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Tides_Blue_Borealis_17Jewels_1974"),
  "Novart/Novart_Tides_Golden_Linen_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Tides_Golden_Linen_17Jewels_1974"),
  "Novart/Novart_Tides_Yellow_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Tides_Yellow_17Jewels_1974"),
  "Novart/Novart_Vitesse_Blue_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Vitesse_Blue_17Jewels_1974"),
  "Novart/Novart_Vitesse_Red_17Jewels_1974": () =>
    import("./watchModels/Novart/Novart_Vitesse_Red_17Jewels_1974"),
  "Olma/Olma_Imperius_1130_1946": () => import("./watchModels/Olma/Olma_Imperius_1130_1946"),
  "Omega/Omega_166041_Cal_30T2_1946": () =>
    import("./watchModels/Omega/Omega_166041_Cal_30T2_1946"),
  "Omega/Omega_1960122_Cal_1370_1977": () =>
    import("./watchModels/Omega/Omega_1960122_Cal_1370_1977"),
  "Omega/Omega_Constellation_COSC_153_020_1967": () =>
    import("./watchModels/Omega/Omega_Constellation_COSC_153_020_1967"),
  "Omega/Omega_DeVille_1910077_Cal_1365_1982": () =>
    import("./watchModels/Omega/Omega_DeVille_1910077_Cal_1365_1982"),
  "Omega/Omega_DeVille_1910167_Cal_1365_1976": () =>
    import("./watchModels/Omega/Omega_DeVille_1910167_Cal_1365_1976"),
  "Omega/Omega_DeVille_Lomgchamp_1910198_Cal_1430_1988": () =>
    import("./watchModels/Omega/Omega_DeVille_Lomgchamp_1910198_Cal_1430_1988"),
  "Omega/Omega_Geneve_Automatic_Cal_1022_1973": () =>
    import("./watchModels/Omega/Omega_Geneve_Automatic_Cal_1022_1973"),
  "Omega/Omega_Geneve_Cal_268_1961": () => import("./watchModels/Omega/Omega_Geneve_Cal_268_1961"),
  "Omega/Omega_Geneve_Cal_565_166_041__1969": () =>
    import("./watchModels/Omega/Omega_Geneve_Cal_565_166_041__1969"),
  "Omega/Omega_Olympia_Albertville_3000_386_1031_1992": () =>
    import("./watchModels/Omega/Omega_Olympia_Albertville_3000_386_1031_1992"),
  "Omega/Omega_Olympia_Albertville_500_386_1031_1992": () =>
    import("./watchModels/Omega/Omega_Olympia_Albertville_500_386_1031_1992"),
  "Omega/Omega_Olympia_Calgary_Seoul_1988": () =>
    import("./watchModels/Omega/Omega_Olympia_Calgary_Seoul_1988"),
  "Omega/Omega_Polaris_396_1022_1987": () =>
    import("./watchModels/Omega/Omega_Polaris_396_1022_1987"),
  "Omega/Omega_Polaris_Calendar_396_1222_1987": () =>
    import("./watchModels/Omega/Omega_Polaris_Calendar_396_1222_1987"),
  "Omega/Omega_Polaris_Chrono_White_386_1031_1992": () =>
    import("./watchModels/Omega/Omega_Polaris_Chrono_White_386_1031_1992"),
  "Omega/Omega_Polaris_GMT_2_396_1122_1987": () =>
    import("./watchModels/Omega/Omega_Polaris_GMT_2_396_1122_1987"),
  "Omega/Omega_Polaris_GMT_396_1122_1987": () =>
    import("./watchModels/Omega/Omega_Polaris_GMT_396_1122_1987"),
  "Omega/Omega_Polaris_MultiFunction_386_0822_1986": () =>
    import("./watchModels/Omega/Omega_Polaris_MultiFunction_386_0822_1986"),
  "Omega/Omega_Polaris_MultiFunction_386_0826_1988": () =>
    import("./watchModels/Omega/Omega_Polaris_MultiFunction_386_0826_1988"),
  "Omega/Omega_Polaris_MultiFunction_386_0826_plated_1988": () =>
    import("./watchModels/Omega/Omega_Polaris_MultiFunction_386_0826_plated_1988"),
  "Omega/Omega_Polaris_Titanium_396_1100_1984": () =>
    import("./watchModels/Omega/Omega_Polaris_Titanium_396_1100_1984"),
  "Omega/Omega_Seamaster_120M_1438_1993": () =>
    import("./watchModels/Omega/Omega_Seamaster_120M_1438_1993"),
  "Omega/Omega_Seamaster_1960079_1977": () =>
    import("./watchModels/Omega/Omega_Seamaster_1960079_1977"),
  "Omega/Omega_Seamaster_Cal_267_1956": () =>
    import("./watchModels/Omega/Omega_Seamaster_Cal_267_1956"),
  "Omega/Omega_Seamaster_Jumbo_Cal_265_1950": () =>
    import("./watchModels/Omega/Omega_Seamaster_Jumbo_Cal_265_1950"),
  "Omega/Omega_Seamaster_cross_hair_14740_Cal_610_1960": () =>
    import("./watchModels/Omega/Omega_Seamaster_cross_hair_14740_Cal_610_1960"),
  "Omega/Omega_Speedmaster_Racing_Schumacher_2000_F1_World_Champion_2000": () =>
    import("./watchModels/Omega/Omega_Speedmaster_Racing_Schumacher_2000_F1_World_Champion_2000"),
  "Omega/Omega_Speedmaster_mk40_triple_date_1998": () =>
    import("./watchModels/Omega/Omega_Speedmaster_mk40_triple_date_1998"),
  "Omega/Omega_Speedmaster_reduced_1998": () =>
    import("./watchModels/Omega/Omega_Speedmaster_reduced_1998"),
  "Omega/Omega_StayBrite_CK3416_T17_1934": () =>
    import("./watchModels/Omega/Omega_StayBrite_CK3416_T17_1934"),
  "Omega/Omega_StayBrite_Honeycomb_1952": () =>
    import("./watchModels/Omega/Omega_StayBrite_Honeycomb_1952"),
  "Omega/Omega_Trésor_Cal_266_1952": () => import("./watchModels/Omega/Omega_Trésor_Cal_266_1952"),
  "Omodox/Omodox_Precision_17Rubis_1950": () =>
    import("./watchModels/Omodox/Omodox_Precision_17Rubis_1950"),
  "One/One_Voyager_Chrono_2014": () => import("./watchModels/One/One_Voyager_Chrono_2014"),
  "Orfina/Orfina_Pilot_Chronograph_17J_1945": () =>
    import("./watchModels/Orfina/Orfina_Pilot_Chronograph_17J_1945"),
  "Orient/Orient_Multi_year_calendar_EU3B0_1998": () =>
    import("./watchModels/Orient/Orient_Multi_year_calendar_EU3B0_1998"),
  "Philipe_Watch/Philipe_Watch_AQ_1000_1996": () =>
    import("./watchModels/Philipe_Watch/Philipe_Watch_AQ_1000_1996"),
  "Poljot/Poljot_Jetfighter_Limited_2018": () =>
    import("./watchModels/Poljot/Poljot_Jetfighter_Limited_2018"),
  "Porsche_Design/Porsche_Design_911_GT2_Cup_1998": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_911_GT2_Cup_1998"),
  "Porsche_Design/Porsche_Design_911_JP_Jarier_1998": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_911_JP_Jarier_1998"),
  "Porsche_Design/Porsche_Design_Dashboard_P6612_14_Titanium_2005": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_Dashboard_P6612_14_Titanium_2005"),
  "Porsche_Design/Porsche_Design_Drivers_Collection_Cayenne_2016": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_Drivers_Collection_Cayenne_2016"),
  "Porsche_Design/Porsche_Design_GT2_Cup_Limited_Edition_1998": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_GT2_Cup_Limited_Edition_1998"),
  "Porsche_Design/Porsche_Design_P6612_10_1_Black_Titanium_2005": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_P6612_10_1_Black_Titanium_2005"),
  "Porsche_Design/Porsche_Design_P6612_14_2_Red_Titanium_2012": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_P6612_14_2_Red_Titanium_2012"),
  "Porsche_Design/Porsche_Design_P6612_Titanium_2005": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_P6612_Titanium_2005"),
  "Porsche_Design/Porsche_Design_P6620_Blue_Titanium_2012": () =>
    import("./watchModels/Porsche_Design/Porsche_Design_P6620_Blue_Titanium_2012"),
  "Provita/Provita_Automatic_25J_1969": () =>
    import("./watchModels/Provita/Provita_Automatic_25J_1969"),
  "Pryngeps/Pryngeps_Automatic_Chronograph_Valjoux_7750": () =>
    import("./watchModels/Pryngeps/Pryngeps_Automatic_Chronograph_Valjoux_7750"),
  "Pryngeps/Pryngeps_CR763_OS60_2001": () =>
    import("./watchModels/Pryngeps/Pryngeps_CR763_OS60_2001"),
  "Pryngeps/Pryngeps_Regolo_1467_1990": () =>
    import("./watchModels/Pryngeps/Pryngeps_Regolo_1467_1990"),
  "Pryngeps/Pryngeps_Regolo_1467_1991": () =>
    import("./watchModels/Pryngeps/Pryngeps_Regolo_1467_1991"),
  "Pryngeps/Pryngeps_Regolo_Triple_Calendar_1992": () =>
    import("./watchModels/Pryngeps/Pryngeps_Regolo_Triple_Calendar_1992"),
  "Pryngeps/Pryngeps_Timonier_Rattrapante_2000": () =>
    import("./watchModels/Pryngeps/Pryngeps_Timonier_Rattrapante_2000"),
  "Radiant/Radiant_Sport_Rally_Rattrapante_1996": () =>
    import("./watchModels/Radiant/Radiant_Sport_Rally_Rattrapante_1996"),
  "Raymond_Weil/Raymond_Weil_2809_Automatic_1988": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_2809_Automatic_1988"),
  "Raymond_Weil/Raymond_Weil_Amadeus_200_2005": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Amadeus_200_2005"),
  "Raymond_Weil/Raymond_Weil_Maestro_2834_Automatic_2008": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Maestro_2834_Automatic_2008"),
  "Raymond_Weil/Raymond_Weil_Maestro_2847_Automatic_2016": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Maestro_2847_Automatic_2016"),
  "Raymond_Weil/Raymond_Weil_Maestro_ETA_2834_Automatic_2008": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Maestro_ETA_2834_Automatic_2008"),
  "Raymond_Weil/Raymond_Weil_Saxo_9520_2007": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Saxo_9520_2007"),
  "Raymond_Weil/Raymond_Weil_Tango_Diver_2007": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Tango_Diver_2007"),
  "Raymond_Weil/Raymond_Weil_Tradition_Mecanique_2892_1992": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Tradition_Mecanique_2892_1992"),
  "Raymond_Weil/Raymond_Weil_Tradition_Mecanique_7760_1990": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Tradition_Mecanique_7760_1990"),
  "Raymond_Weil/Raymond_Weil_Tradition_Mecanique_7760_A290703_1990": () =>
    import("./watchModels/Raymond_Weil/Raymond_Weil_Tradition_Mecanique_7760_A290703_1990"),
  "Relide/Relide_Militare_1955": () => import("./watchModels/Relide/Relide_Militare_1955"),
  "Romar/Romar_Incabloc_17Jewels_1976": () =>
    import("./watchModels/Romar/Romar_Incabloc_17Jewels_1976"),
  "Romar/Romar_Incabloc_17Jewels_Green_1976": () =>
    import("./watchModels/Romar/Romar_Incabloc_17Jewels_Green_1976"),
  "Rone/Rone_Calendar_Pointer_1950": () => import("./watchModels/Rone/Rone_Calendar_Pointer_1950"),
  "Said/Said_Blue_Linen_Unitas_6325_1973": () =>
    import("./watchModels/Said/Said_Blue_Linen_Unitas_6325_1973"),
  "Saint_Honore/Saint_Honore_Classic_Rattrapante_1996": () =>
    import("./watchModels/Saint_Honore/Saint_Honore_Classic_Rattrapante_1996"),
  "Sector/Sector_250_Chrono_Alarm_2012": () =>
    import("./watchModels/Sector/Sector_250_Chrono_Alarm_2012"),
  "Seiko/Seiko_4004_1976": () => import("./watchModels/Seiko/Seiko_4004_1976"),
  "Seiko/Seiko_6306_7001_1976": () => import("./watchModels/Seiko/Seiko_6306_7001_1976"),
  "Seiko/Seiko_6M13_0010_Perpetual_Calendar_1992": () =>
    import("./watchModels/Seiko/Seiko_6M13_0010_Perpetual_Calendar_1992"),
  "Seiko/Seiko_6M13_Perpetual_Calendar_1994": () =>
    import("./watchModels/Seiko/Seiko_6M13_Perpetual_Calendar_1994"),
  "Seiko/Seiko_6M25_Chronograph_1992": () =>
    import("./watchModels/Seiko/Seiko_6M25_Chronograph_1992"),
  "Seiko/Seiko_7T32_7410_Moonphase_1991": () =>
    import("./watchModels/Seiko/Seiko_7T32_7410_Moonphase_1991"),
  "Seiko/Seiko_8M25_Age_Of_Discoveries.1992": () =>
    import("./watchModels/Seiko/Seiko_8M25_Age_Of_Discoveries.1992"),
  "Seiko/Seiko_V732_0390_1990": () => import("./watchModels/Seiko/Seiko_V732_0390_1990"),
  "Signo/Signo_Small_Seconds_1947": () => import("./watchModels/Signo/Signo_Small_Seconds_1947"),
  "Tag_Heuer/Heuer_Airline_Professional_895513_1985": () =>
    import("./watchModels/Tag_Heuer/Heuer_Airline_Professional_895513_1985"),
  "Tag_Heuer/Tag_Heuer_Aquaracer_CN2111_2005": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Aquaracer_CN2111_2005"),
  "Tag_Heuer/Tag_Heuer_Aquaracer_WAF1010_2010": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Aquaracer_WAF1010_2010"),
  "Tag_Heuer/Tag_Heuer_Carrera_Automatic_Caliber_5_2007": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Carrera_Automatic_Caliber_5_2007"),
  "Tag_Heuer/Tag_Heuer_Formula_1_Indy_500_2016": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_Indy_500_2016"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WA1211_Tritium_1995": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WA1211_Tritium_1995"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WA1212_Tritium_1995": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WA1212_Tritium_1995"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WA1218_1995": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WA1218_1995"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WA1219_1995": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WA1219_1995"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WA1219_R_1995": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WA1219_R_1995"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WAC1210_2008": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WAC1210_2008"),
  "Tag_Heuer/Tag_Heuer_Formula_1_WAC1212_2008": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Formula_1_WAC1212_2008"),
  "Tag_Heuer/Tag_Heuer_Kirium_Formula_1_Chronograph_2001": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Kirium_Formula_1_Chronograph_2001"),
  "Tag_Heuer/Tag_Heuer_LWO_283_875206_1991": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_LWO_283_875206_1991"),
  "Tag_Heuer/Tag_Heuer_Monza_Automatic_Cal_6_2005": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Monza_Automatic_Cal_6_2005"),
  "Tag_Heuer/Tag_Heuer_Monza_Classic_2005": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Monza_Classic_2005"),
  "Tag_Heuer/Tag_Heuer_ProChrono_2620061_1987": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_ProChrono_2620061_1987"),
  "Tag_Heuer/Tag_Heuer_ProChrono_2720061_1985": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_ProChrono_2720061_1985"),
  "Tag_Heuer/Tag_Heuer_ProChrono_2720061_LWO_185_1986": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_ProChrono_2720061_LWO_185_1986"),
  "Tag_Heuer/Tag_Heuer_Professional_1500_1997": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Professional_1500_1997"),
  "Tag_Heuer/Tag_Heuer_Professional_2000_1999": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Professional_2000_1999"),
  "Tag_Heuer/Tag_Heuer_Professional_2000_Auto_1991": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Professional_2000_Auto_1991"),
  "Tag_Heuer/Tag_Heuer_Professional_2000_CK1111_1996": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Professional_2000_CK1111_1996"),
  "Tag_Heuer/Tag_Heuer_S-EL_Digitial_Senna_1990": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_S-EL_Digitial_Senna_1990"),
  "Tag_Heuer/Tag_Heuer_Senna_Link_CT5114_2003": () =>
    import("./watchModels/Tag_Heuer/Tag_Heuer_Senna_Link_CT5114_2003"),
  "Taunus/Taunus_Calendar_17Rubis_1975": () =>
    import("./watchModels/Taunus/Taunus_Calendar_17Rubis_1975"),
  "Tecnal/Tecnal_Green_Abyss_Duromat_7522_1972": () =>
    import("./watchModels/Tecnal/Tecnal_Green_Abyss_Duromat_7522_1972"),
  "Timex/Kelton_M24_Sub_Dive_1970": () => import("./watchModels/Timex/Kelton_M24_Sub_Dive_1970"),
  "Timex/Timex_Marlin_1980": () => import("./watchModels/Timex/Timex_Marlin_1980"),
  "Timex/Timex_T2M515_Power_Reserve_2008": () =>
    import("./watchModels/Timex/Timex_T2M515_Power_Reserve_2008"),
  "Tissot/Tissot_ PR_100_Chronograph_2005": () =>
    import("./watchModels/Tissot/Tissot_ PR_100_Chronograph_2005"),
  "Tissot/Tissot_Antimagnetic_1946": () => import("./watchModels/Tissot/Tissot_Antimagnetic_1946"),
  "Tissot/Tissot_Antimagnetic_1947_white": () =>
    import("./watchModels/Tissot/Tissot_Antimagnetic_1947_white"),
  "Tissot/Tissot_Antimagnetic_27_2_1940": () =>
    import("./watchModels/Tissot/Tissot_Antimagnetic_27_2_1940"),
  "Tissot/Tissot_Antimagnetic_Tuxedo_1943": () =>
    import("./watchModels/Tissot/Tissot_Antimagnetic_Tuxedo_1943"),
  "Tissot/Tissot_Antimagnetic_Tuxedo_Cal_272_1942": () =>
    import("./watchModels/Tissot/Tissot_Antimagnetic_Tuxedo_Cal_272_1942"),
  "Tissot/Tissot_Automatic_Bumper_31_21_1946": () =>
    import("./watchModels/Tissot/Tissot_Automatic_Bumper_31_21_1946"),
  "Tissot/Tissot_Ballade_C229399C_Lady_Auto_2005": () =>
    import("./watchModels/Tissot/Tissot_Ballade_C229399C_Lady_Auto_2005"),
  "Tissot/Tissot_Ballade_C279379_Auto_2002": () =>
    import("./watchModels/Tissot/Tissot_Ballade_C279379_Auto_2002"),
  "Tissot/Tissot_Ballade_Chrono_2012": () =>
    import("./watchModels/Tissot/Tissot_Ballade_Chrono_2012"),
  "Tissot/Tissot_Ballade_Chrono_2012_two_tone": () =>
    import("./watchModels/Tissot/Tissot_Ballade_Chrono_2012_two_tone"),
  "Tissot/Tissot_Ballade_Lady_C227_327_2002": () =>
    import("./watchModels/Tissot/Tissot_Ballade_Lady_C227_327_2002"),
  "Tissot/Tissot_Ballade_Seastar_1995": () =>
    import("./watchModels/Tissot/Tissot_Ballade_Seastar_1995"),
  "Tissot/Tissot_Fetes_Des_Vignerons_2019": () =>
    import("./watchModels/Tissot/Tissot_Fetes_Des_Vignerons_2019"),
  "Tissot/Tissot_Fetes_Des_Vignerons_2019_2": () =>
    import("./watchModels/Tissot/Tissot_Fetes_Des_Vignerons_2019_2"),
  "Tissot/Tissot_Heritage_130th_Anniversary_7734_1983": () =>
    import("./watchModels/Tissot/Tissot_Heritage_130th_Anniversary_7734_1983"),
  "Tissot/Tissot_Heritage_150th_COSC_2003": () =>
    import("./watchModels/Tissot/Tissot_Heritage_150th_COSC_2003"),
  "Tissot/Tissot_Heritage_150th_COSC_884_8888_2003": () =>
    import("./watchModels/Tissot/Tissot_Heritage_150th_COSC_884_8888_2003"),
  "Tissot/Tissot_Heritage_1944_COSC_2011": () =>
    import("./watchModels/Tissot/Tissot_Heritage_1944_COSC_2011"),
  "Tissot/Tissot_Heritage_Telemeter_COSC_2009": () =>
    import("./watchModels/Tissot/Tissot_Heritage_Telemeter_COSC_2009"),
  "Tissot/Tissot_Heritage_Visodate_2012": () =>
    import("./watchModels/Tissot/Tissot_Heritage_Visodate_2012"),
  "Tissot/Tissot_L396_Chrono_1993": () => import("./watchModels/Tissot/Tissot_L396_Chrono_1993"),
  "Tissot/Tissot_Le_Locle_Auto_2007": () =>
    import("./watchModels/Tissot/Tissot_Le_Locle_Auto_2007"),
  "Tissot/Tissot_Le_Locle_Seastar_1985": () =>
    import("./watchModels/Tissot/Tissot_Le_Locle_Seastar_1985"),
  "Tissot/Tissot_Luxury_Powermatic_2012": () =>
    import("./watchModels/Tissot/Tissot_Luxury_Powermatic_2012"),
  "Tissot/Tissot_Navigator_Panda_Automatic_Lemania_1341_1974": () =>
    import("./watchModels/Tissot/Tissot_Navigator_Panda_Automatic_Lemania_1341_1974"),
  "Tissot/Tissot_Nuevo_Horizonte_1958": () =>
    import("./watchModels/Tissot/Tissot_Nuevo_Horizonte_1958"),
  "Tissot/Tissot_Nuevo_Horizonte_1960": () =>
    import("./watchModels/Tissot/Tissot_Nuevo_Horizonte_1960"),
  "Tissot/Tissot_PRC_200_T461_2010": () => import("./watchModels/Tissot/Tissot_PRC_200_T461_2010"),
  "Tissot/Tissot_PRS_200_T362462K_2010": () =>
    import("./watchModels/Tissot/Tissot_PRS_200_T362462K_2010"),
  "Tissot/Tissot_PRS_200_T362462_2011": () =>
    import("./watchModels/Tissot/Tissot_PRS_200_T362462_2011"),
  "Tissot/Tissot_PRS_200_T362462_2012": () =>
    import("./watchModels/Tissot/Tissot_PRS_200_T362462_2012"),
  "Tissot/Tissot_PRS_516_Alpine_Edition_2019": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_Alpine_Edition_2019"),
  "Tissot/Tissot_PRS_516_J562662_2005": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_J562662_2005"),
  "Tissot/Tissot_PRS_516_NASCAR_Racing_Chronograph_2014": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_NASCAR_Racing_Chronograph_2014"),
  "Tissot/Tissot_PRS_516_Retrograde_2005": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_Retrograde_2005"),
  "Tissot/Tissot_PRS_516_Special_Nascar_Edition_2014": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_Special_Nascar_Edition_2014"),
  "Tissot/Tissot_PRS_516_Valjoux_2009": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_Valjoux_2009"),
  "Tissot/Tissot_PRS_516_Valjoux_2011": () =>
    import("./watchModels/Tissot/Tissot_PRS_516_Valjoux_2011"),
  "Tissot/Tissot_PRX_P376_Auto_7750_1993": () =>
    import("./watchModels/Tissot/Tissot_PRX_P376_Auto_7750_1993"),
  "Tissot/Tissot_PRX_P475_Chrono_1991": () =>
    import("./watchModels/Tissot/Tissot_PRX_P475_Chrono_1991"),
  "Tissot/Tissot_PR_516_LeLocle_1979": () =>
    import("./watchModels/Tissot/Tissot_PR_516_LeLocle_1979"),
  "Tissot/Tissot_Quartz_1979": () => import("./watchModels/Tissot/Tissot_Quartz_1979"),
  "Tissot/Tissot_SeaStar_LeLocle_1979": () =>
    import("./watchModels/Tissot/Tissot_SeaStar_LeLocle_1979"),
  "Tissot/Tissot_SeaStar_Quartz_1978": () =>
    import("./watchModels/Tissot/Tissot_SeaStar_Quartz_1978"),
  "Tissot/Tissot_Seastar_Automatic_1974": () =>
    import("./watchModels/Tissot/Tissot_Seastar_Automatic_1974"),
  "Tissot/Tissot_Seastar_Eletronic_1970": () =>
    import("./watchModels/Tissot/Tissot_Seastar_Eletronic_1970"),
  "Tissot/Tissot_Seastar_Lobster_Automatic_1974": () =>
    import("./watchModels/Tissot/Tissot_Seastar_Lobster_Automatic_1974"),
  "Tissot/Tissot_Seastar_Navigator_Chrono_1974": () =>
    import("./watchModels/Tissot/Tissot_Seastar_Navigator_Chrono_1974"),
  "Tissot/Tissot_Seastar_PR516_1967": () =>
    import("./watchModels/Tissot/Tissot_Seastar_PR516_1967"),
  "Tissot/Tissot_Seastar_PR516_1970": () =>
    import("./watchModels/Tissot/Tissot_Seastar_PR516_1970"),
  "Tissot/Tissot_Seastar_PR516_Auto_1965": () =>
    import("./watchModels/Tissot/Tissot_Seastar_PR516_Auto_1965"),
  "Tissot/Tissot_Seastar_PR516_GL_1968": () =>
    import("./watchModels/Tissot/Tissot_Seastar_PR516_GL_1968"),
  "Tissot/Tissot_Seastar_PR516_GL_1971": () =>
    import("./watchModels/Tissot/Tissot_Seastar_PR516_GL_1971"),
  "Tissot/Tissot_Seastar_PR516_GL_784_1971": () =>
    import("./watchModels/Tissot/Tissot_Seastar_PR516_GL_784_1971"),
  "Tissot/Tissot_Seastar_Seven_1963": () =>
    import("./watchModels/Tissot/Tissot_Seastar_Seven_1963"),
  "Tissot/Tissot_Seastar_T12_Auto_1964": () =>
    import("./watchModels/Tissot/Tissot_Seastar_T12_Auto_1964"),
  "Tissot/Tissot_Seastar_T12_Chrono_Lemania_1972": () =>
    import("./watchModels/Tissot/Tissot_Seastar_T12_Chrono_Lemania_1972"),
  "Tissot/Tissot_Sports_E662_2000": () => import("./watchModels/Tissot/Tissot_Sports_E662_2000"),
  "Tissot/Tissot_Sports_E662_Chrono_1995": () =>
    import("./watchModels/Tissot/Tissot_Sports_E662_Chrono_1995"),
  "Tissot/Tissot_Sports_E662_Chrono_2000": () =>
    import("./watchModels/Tissot/Tissot_Sports_E662_Chrono_2000"),
  "Tissot/Tissot_T-Race_T472S_2008": () => import("./watchModels/Tissot/Tissot_T-Race_T472S_2008"),
  "Tissot/Tissot_T-Touch_2009": () => import("./watchModels/Tissot/Tissot_T-Touch_2009"),
  "Tissot/Tissot_T-Touch_Expert_Solar_2020": () =>
    import("./watchModels/Tissot/Tissot_T-Touch_Expert_Solar_2020"),
  "Tissot/Tissot_TClassic_Dream_2014": () =>
    import("./watchModels/Tissot/Tissot_TClassic_Dream_2014"),
  "Tissot/Tissot_TClassic_Tradition_2021": () =>
    import("./watchModels/Tissot/Tissot_TClassic_Tradition_2021"),
  "Tissot/Tissot_T_Sports_GMT_Titanium_2015": () =>
    import("./watchModels/Tissot/Tissot_T_Sports_GMT_Titanium_2015"),
  "Tissot/Tissot_T_Tracx_MOP_2005": () => import("./watchModels/Tissot/Tissot_T_Tracx_MOP_2005"),
  "Tissot/Tissot_V8_S792862N_2014": () => import("./watchModels/Tissot/Tissot_V8_S792862N_2014"),
  "Tissot/Tissot_Visodate_1955": () => import("./watchModels/Tissot/Tissot_Visodate_1955"),
  "Tissot/Tissot_Visodate_1957": () => import("./watchModels/Tissot/Tissot_Visodate_1957"),
  "Tissot/Tissot_Visodate_Automatic_1958": () =>
    import("./watchModels/Tissot/Tissot_Visodate_Automatic_1958"),
  "Tissoure/Tissoure_Cronometro_17J_1975": () =>
    import("./watchModels/Tissoure/Tissoure_Cronometro_17J_1975"),
  "Titus/Titus_Chronograph_L48_1950": () =>
    import("./watchModels/Titus/Titus_Chronograph_L48_1950"),
  "Titus/Titus_Tuning_Fork_F300Hz_1970": () =>
    import("./watchModels/Titus/Titus_Tuning_Fork_F300Hz_1970"),
  "Tonino_Lamborghini/Tonino_Lamborghini_Bologna_II_2011": () =>
    import("./watchModels/Tonino_Lamborghini/Tonino_Lamborghini_Bologna_II_2011"),
  "Tourist/Tourist_Ancre_17Rubis_1950": () =>
    import("./watchModels/Tourist/Tourist_Ancre_17Rubis_1950"),
  "Universal_Geneve/Universal_Geneve_Chrono_875214_1995": () =>
    import("./watchModels/Universal_Geneve/Universal_Geneve_Chrono_875214_1995"),
  "Universal_Geneve/Universal_Geneve_Mecanique_cal_262_1942": () =>
    import("./watchModels/Universal_Geneve/Universal_Geneve_Mecanique_cal_262_1942"),
  "Utina/Utina_Enamel_Dial_FE233_1968": () =>
    import("./watchModels/Utina/Utina_Enamel_Dial_FE233_1968"),
  "Utina/Utina_Sunburst_FE233_1972": () => import("./watchModels/Utina/Utina_Sunburst_FE233_1972"),
  "Zenith/Zenith_El_Primero_ChronoMaster_2010": () =>
    import("./watchModels/Zenith/Zenith_El_Primero_ChronoMaster_2010"),
  "Zenith/Zenith_El_Primero_Port_Royal_V_2005": () =>
    import("./watchModels/Zenith/Zenith_El_Primero_Port_Royal_V_2005"),
  "Zenith/Zenith_Militare_Cal_106_1945": () =>
    import("./watchModels/Zenith/Zenith_Militare_Cal_106_1945"),
  "Zenith/Zenith_Pilot_P12_1945": () => import("./watchModels/Zenith/Zenith_Pilot_P12_1945"),
  "Zodiac/Zodiac_Sea_Dragon_ZO2237_2014": () =>
    import("./watchModels/Zodiac/Zodiac_Sea_Dragon_ZO2237_2014"),
};
