export const BrandsEnum = {
  ADMES: "Admes",
  AMER: "Amer",
  AMYRIA: "Amyria",
  ARGUS: "Argus",
  BELEX: "Belex",
  BERGEON: "Bergeon",
  BREITLING: "Breitling",
  CALYPSO: "Calypso (Festina Group)",
  CAMEL_TROPHY: "Camel Trophy",
  CUERVO_Y_SOBRINOS: "Cuervo y Sobrinos",
  CAUNY: "Cauny",
  CELSUS: "Celsus",
  CERTINA: "Certina",
  CHOPARD: "Chopard",
  CORTICIMA: "Corticima",
  CRISTAL_WATCH: "Crystal Watch",
  DOXA: "Doxa",
  EBERHARD: "Eberhard",
  ELETTA: "Eletta",
  EMES: "Emes",
  FESTINA: "Festina",
  FERRARI: "Ferrari",
  FONTAINE: "Fontaine",
  FORTIS: "Fortis",
  GREENWICH: "Greenwich",
  BARRETT: "Barrett",
  HELMA: "Helma",
  HEUER: "Heuer",
  HERMES: "Hermes",
  HIPCO: "Hipco",
  JAGUAR_FRAGRANCES: "Jaguar Fragrances",
  KELTON: "Kelton",
  LANCO: "Lanco",
  LATINO: "Latino",
  LORENZ: "Lorenz",
  LORUS: "Lorus",
  LUCERNE: "Lucerne",
  MARTINI: "Martini",
  MAURICE_LACROIX: "Maurice Lacroix",
  MERCEDES_BENZ: "Mercedes Benz",
  MASERATI: "Maserati",
  MIURA: "Miura",
  MONUMENTAL: "Monumental",
  MOTORSPORT_BRANDS: "MotorSport Brands",
  NATALIS: "Natalis",
  NOBREZA: "Nobreza",
  NOVART: "Novart",
  OLMA: "Olma",
  ORFINA: "Orfina",
  OMEGA: "Omega",
  OMODOX: "Omodox",
  ONE: "One",
  ORIENT: "Orient",
  PHILIP_WATCH: "Philip Watch",
  POLJOT: "Poljot",
  PORSCHE_DESIGN: "Porsche Design",
  PORTUGUESE_BRANDS: "Portuguese Brands",
  PROVITA: "Provita",
  PRYNGEPS: "Pryngeps",
  RAYMOND_WEIL: "Raymond Weil",
  RELIDE: "Relide",
  ROMAR: "Romar",
  RONE: "Rone",
  ROYAL_GEOGRAPHICAL_SOCIETY: "Royal Geographical Society",
  SEIKO: "Seiko",
  SECTOR: "Sector",
  SIGNO: "Signo",
  SOLVIL_ET_TITUS: "Solvil et Titus",
  TAG_HEUER: "Tag Heuer",
  TAUNUS: "Taunus",
  TIMEX: "Timex",
  TISSOT: "Tissot",
  TISSOURE: "Tissoure",
  TONINO_LAMBORGHINI: "Tonino Lamborghini",
  TOURIST: "Tourist",
  UNIVERSAL_GENEVE: "Universal Geneve",
  ZENITH: "Zenith",
  ZODIAC: "Zodiac",
};
