export const CaliberBrandsEnum = {
  AS: "A. Schild",
  CERTINA: "Certina",
  DUBOIS_DEPRAZ: "Dubois Depraz",
  DOXA: "Doxa",
  EBERHARD: "Eberhard",
  ETA: "ETA",
  EXCELSIOR_PARK: "Excelsior Park",
  FE: "FE (France Ebauche)",
  FHF: "FHF (Fabrique d'Horlogerie de Fontainemelon)",
  FORTIS: "Fortis",
  LANDERON: "Landeron",
  LEMANIA: "Lemania",
  MIYOTA: "Miyota",
  OMEGA: "Omega",
  ORIENT: "Orient",
  POLJOT: "Poljot",
  RONDA: "Ronda",
  SEAGULL: "Seagull",
  SEIKO: "Seiko",
  SELLITA: "Sellita",
  TIMEX: "Timex",
  TISSOT: "Tissot",
  UNITAS: "Unitas",
  VALJOUX: "Valjoux",
  VENUS: "Venus",
  UNIVERSAL_GENEVE: "Universal Geneve",
  ZENITH: "Zenith",
};

export const FrequencyEnum = {
  F_18000: "18000 A/h",
  F_19800: "19800 A/h",
  F_21600: "21600 A/h",
  F_28800: "28800 A/h",
  F_36600: "36600 A/h",
};

export const JewelsNumberEnum = {
  J_0: "Zero (None) Jewels",
  J_4: "4 (Four) Jewels",
  J_5: "5 (Five) Jewels",
  J_6: "6 (Six) Jewels",
  J_7: "7 (Seven) Jewels",
  J_13: "13 (Thirteen) Jewels",
  J_15: "15 (Fifteen) Jewels",
  J_16: "16 (Sixteen) Jewels",
  J_17: "17 (Seventeen) Jewels",
  J_21: "21 (Twenty-One) Jewels",
  J_22: "22 (Twenty-Two) Jewels",
  J_23: "23 (Twenty-Three) Jewels",
  J_24: "23 (Twenty-Four) Jewels",
  J_25: "25 (Twenty-Five) Jewels",
  J_26: "26 (Twenty-Six) Jewels",
  J_27: "27 (Twenty-Seven) Jewels",
  J_28: "28 (Twenty-Eight) Jewels",
  J_30: "30 (Thirty) Jewels",
  J_31: "31 (Thirty-One) Jewels",
  J_37: "37 (Thirty-Seven) Jewels",
  J_39: "39 (Thirty-Nine) Jewels",
  J_40: "40 (Forty) Jewels",
};

export const ReserveHoursEnum = {
  R_40: "40 Hours",
  R_38: "38 Hours",
  R_41: "41 Hours",
  R_42: "42 Hours",
  R_44: "44 Hours",
  R_45: "45 Hours",
  R_47: "47 Hours",
  R_50: "50 Hours",
  R_60: "60 Hours",
  R_80: "80 Hours",
};
