export const CaseFinishingEnum = {
  NONE: "-",
  POLISHED: "Polished",
  VERTICAL_BRUSHED: "Vertical Brushed",
  VERTICAL_POLISHED: "Vertical Polished",
  HORIZONTAL_BRUSHED: "Horizontal Brushed",
  CIRCULAR_BRUSHED: "Circular Brushed",
  CIRCULAR_POLISHED: "Circular Polished",
  RADIAL_BRUSHED: "Radial Brushed",
  RADIAL_POLISHED: "Subtle Radial Polished",
  SUNSHINE_BRUSHED: "Sunshine Brushed",
  SANDBLASTED: "Sandblasted",
  SATIN_MATTE: "Satin Matte",
  MATTE: "Matte",
  BLACK_PVD: "Black PVD Coating",
  CHROMED: "Chromed",
  BRONZE_PLATED: "Bronze Plated",
  GUN_METAL: "Gun-metal Finish",
  BRUSHED: "Brushed",
};
