export const FinishingDetailsEnum = {
  NONE: "None",
  APPLIED_INDECES: "Applied Indeces",
  RADIAL_BRUSHED_EFFECT: "Radial Brushed Effect",
  METALLIC_COLOR: "Metallic",
  WEB_TEXTURE_DIAL: "Web Textured Dial",
  TEXTURED: "Textured Dial",
  POWDER_EFFECT: "Powder Textured Dial",
  ENAMEL: "Enamel Dial",
  CARBON_FIBER: "Carbon Fiber Pattern",
  VERTICAL_BRUSHED: "Vertical Brushed Patterm",
  TRITIUM_MARKERS: "Tritium Markers",
  SNOWFLAKE_PATTERN: "Snowflake Pattern Dial",
  GOLD_DETAILS: "Gold Details",
  DETAILED_SUB_DIALS: "Detailed Subdials",
  PAN_DIAL: "Pan Dial",
  GRANITE: "Granite Dial",
  HONEYCOMB: "Honeycomb Patterm",
  CLOUD_DE_PARIS: "Clous de Paris dial",
  TUXEDO: "Tuxedo Dial",
};
